app = "lms-backend-qhvvka"
console_command = "/code/manage.py shell"
primary_region = "sin"

[deploy]
release_command = "python manage.py migrate"

[env]
PORT = "8000"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[processes]
app = "gunicorn --bind :8000 --workers 2 eccgd_backend.wsgi"
celery = "celery -A eccgd_backend worker --loglevel=INFO"

[[statics]]
guest_path = "/code/static"
tigris_bucket = ""
url_prefix = "/static/"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024