services:
  - type: web
    name: eccgd-lms-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn eccgd_backend.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecggd-postgre-db
          property: connectionString

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true

      - key: DJANGO_ALLOWED_HOSTS
        value: "lms-backend-ioll.onrender.com,lms-backend-sylu.onrender.com"

      - key: DJANGO_SETTINGS_MODULE
        value: "eccgd_backend.settings"
